### ISSUE TITLE
Helper Module Not Found

### ISSUE THREAD

**Issue by hemanticr** [Fettpet/pytorch-crfasrnn#4]
Hi, I'm getting this error:

> File "/content/pytorch-crfasrnn/Permutohedral_Filtering/Permutohedral_Filtering.py", line 7, in <module>
    from Helper.Debug_Tensor import debug_tensor
ModuleNotFoundError: No module named 'Helper'

I think the helper module needs to be uploaded.

**Comment by Fettpet** [comment]
The debug_tensor is not necessary. It prints some statistics about a tensor. It can be removed. I removed it on the master.
